default: &default
  adapter: postgresql
  encoding: unicode
  pool: 100
  timeout: 5000
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: tds_common_lib_dummy_development

test:
  <<: *default
  database: tds_common_lib_dummy_test
  reaping_frequency: 0

