// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TdsCommonLib__ClassTogglerController from "./tds_common_lib/class_toggler_controller.js"
application.register("tds-common-lib--class-toggler", TdsCommonLib__ClassTogglerController)

import TdsCommonLib__ContentLoaderController from "./tds_common_lib/content_loader_controller.js"
application.register("tds-common-lib--content-loader", TdsCommonLib__ContentLoaderController)

import TdsCommonLibBackend__DateRangePickerController from "./tds_common_lib_backend/date_range_picker_controller.js"
application.register("tds-common-lib-backend--date-range-picker", TdsCommonLibBackend__DateRangePickerController)

import TdsCommonLibBackend__DependentSelectController from "./tds_common_lib_backend/dependent_select_controller.js"
application.register("tds-common-lib-backend--dependent-select", TdsCommonLibBackend__DependentSelectController)

import TdsCommonLibBackend__DragAndDropListController from "./tds_common_lib_backend/drag_and_drop_list_controller.js"
application.register("tds-common-lib-backend--drag-and-drop-list", TdsCommonLibBackend__DragAndDropListController)

import TdsCommonLibBackend__FlashController from "./tds_common_lib_backend/flash_controller.js"
application.register("tds-common-lib-backend--flash", TdsCommonLibBackend__FlashController)

import TdsCommonLibBackend__FormController from "./tds_common_lib_backend/form_controller.js"
application.register("tds-common-lib-backend--form", TdsCommonLibBackend__FormController)

import TdsCommonLibBackend__InfiniteItemsFormController from "./tds_common_lib_backend/infinite_items_form_controller.js"
application.register("tds-common-lib-backend--infinite-items-form", TdsCommonLibBackend__InfiniteItemsFormController)

import TdsCommonLibBackend__MarkdownEditorController from "./tds_common_lib_backend/markdown_editor_controller.js"
application.register("tds-common-lib-backend--markdown-editor", TdsCommonLibBackend__MarkdownEditorController)

import TdsCommonLibBackend__NestedFormController from "./tds_common_lib_backend/nested_form_controller.js"
application.register("tds-common-lib-backend--nested-form", TdsCommonLibBackend__NestedFormController)

import TdsCommonLibBackend__RemoteFormController from "./tds_common_lib_backend/remote_form_controller.js"
application.register("tds-common-lib-backend--remote-form", TdsCommonLibBackend__RemoteFormController)

import TdsCommonLibBackend__SavableDateRangeController from "./tds_common_lib_backend/savable_date_range_controller.js"
application.register("tds-common-lib-backend--savable-date-range", TdsCommonLibBackend__SavableDateRangeController)

import TdsCommonLibBackend__SelectpickerController from "./tds_common_lib_backend/selectpicker_controller.js"
application.register("tds-common-lib-backend--selectpicker", TdsCommonLibBackend__SelectpickerController)

import TdsCommonLibBackend__SidebarController from "./tds_common_lib_backend/sidebar_controller.js"
application.register("tds-common-lib-backend--sidebar", TdsCommonLibBackend__SidebarController)
